# Generated by Django 5.2.7 on 2025-10-28 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, unique=True, verbose_name='URL')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Текст статьи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles_images', verbose_name='Изображение')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статью',
                'verbose_name_plural': 'Статьи',
                'db_table': 'article',
            },
        ),
    ]
